# Generated by Django 3.2.8 on 2021-11-07 10:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('follow', '0002_auto_20211103_1524'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_unique_relationship',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followee')},
        ),
    ]
