# Generated by Django 3.2.8 on 2021-11-08 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0003_auto_20211107_1956'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
    ]
