# Generated by Django 3.2.6 on 2021-08-16 02:31

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userid',
            field=models.CharField(default='90ig3ubes6xw', error_messages={'unique': '既に登録されたユーザーIDです。'}, help_text='必須。20文字以内の半角英数字と，アンダースコア（_）のみ。', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['ASCII'], regex='^[a-z_\\d]+\\Z')]),
        ),
    ]
