# Generated by Django 3.2.6 on 2021-08-16 05:39

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='userid',
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default='匿名ユーザー', help_text='必須。50文字以内。', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='zj96jiiexklj', error_messages={'unique': '既に登録されたユーザーIDです。'}, help_text='必須。20文字以内の半角英数字と，アンダースコア（_）のみ。', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['ASCII'], regex='^[a-z_\\d]+\\Z')]),
        ),
    ]
