# Generated by Django 3.2.6 on 2021-08-16 05:43

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='i1iyciqi3sa_', help_text='必須。20文字以内の半角英数字と，アンダースコア（_）のみ。', max_length=20, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['ASCII'], regex='^[a-z_\\d]+\\Z')]),
        ),
    ]
