# Generated by Django 3.2.6 on 2021-08-16 06:03

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='display_name',
            new_name='handle_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_username',
            field=models.CharField(default=None, help_text='ユーザー名', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='lpcusiul2q0z', error_messages={'unique': '既に登録されたユーザーIDです。'}, help_text='必須。20文字以内の半角英数字と，アンダースコア（_）のみ。', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['ASCII'], regex='^[a-z_\\d]+\\Z')]),
        ),
    ]
