# Generated by Django 3.2.6 on 2021-08-17 12:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.customuser')),
                ('handle_name', models.CharField(max_length=50)),
                ('profile', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='display_username',
            field=models.CharField(help_text='入力した生のユーザーID（小文字変換なし）。', max_length=20, unique=True, verbose_name='表示ユーザー名'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='handle_name',
            field=models.CharField(default='匿名ユーザー', help_text='必須。50文字以内。', max_length=50, verbose_name='表示名（ハンドルネーム）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='すべての権限を持つ管理者。', verbose_name='管理者権限'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'max_length': '20文字以内で入力してください。', 'unique': '既に登録されたユーザーIDです。'}, help_text='必須。20文字以内の半角英数字と，アンダースコア（_）のみ。', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['ASCII'], message='半角英数字またはアンダースコア（_）のみで入力してください。', regex='^[\\w]+\\Z')], verbose_name='内部ユーザー名'),
        ),
    ]
