# Generated by Django 3.2.6 on 2021-08-20 01:42

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_is_private'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'ユーザー情報'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'max_length': '20文字以内で入力してください。', 'unique': '既に登録されたユーザーIDです。'}, help_text='20文字以内の半角英数字と，アンダースコア（_）のみ。', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['ASCII'], message='半角英数字またはアンダースコア（_）のみで入力してください。', regex='^[\\w]+\\Z')], verbose_name='内部ユーザー名'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='handle_name',
            field=models.CharField(max_length=50, verbose_name='表示名（ハンドルネーム）'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='非公開'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.TextField(blank=True, null=True, verbose_name='プロフィール'),
        ),
    ]
