# Generated by Django 3.2.6 on 2021-08-20 07:34

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210820_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_private',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='非公開'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='W1jQe8q3RaIj', error_messages={'max_length': '20文字以内で入力してください。', 'unique': '既に登録されたユーザーIDです。'}, help_text='20文字以内の半角英数字と，アンダースコア（_）のみ。', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['ASCII'], message='半角英数字またはアンダースコア（_）のみで入力してください。', regex='^[\\w]+\\Z')], verbose_name='内部ユーザー名'),
        ),
    ]
