# Generated by Django 3.2.6 on 2021-08-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210820_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_initial_username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='changed_initial_username',
            field=models.BooleanField(default=False, verbose_name='初期ユーザー名から変更済'),
        ),
    ]
