# Generated by Django 3.2.6 on 2021-08-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210820_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.TextField(blank=True, null=True, verbose_name='プロフィール'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
