# Generated by Django 3.2.6 on 2021-08-21 03:54

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210820_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_username',
            field=models.CharField(help_text='入力した生のユーザーID（小文字変換なし）。', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['ASCII'], message='半角英数字またはアンダースコア（_）のみで入力してください。', regex='^[\\w]+\\Z')], verbose_name='表示ユーザー名'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='handle_name',
            field=models.CharField(default='匿名ユーザー', help_text='公開される表示名。50文字以内。', max_length=50, verbose_name='表示名（ハンドルネーム）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.TextField(blank=True, default='', verbose_name='プロフィール'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(db_index=True, error_messages={'max_length': '20文字以内で入力してください。', 'unique': '既に登録されたユーザーIDです。'}, help_text='20文字以内の半角英数字と，アンダースコア（_）のみ。', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['ASCII'], message='半角英語小文字・数字またはアンダースコア（_）のみで入力してください。', regex='^[a-z0-9_]+\\Z')], verbose_name='内部ユーザー名'),
        ),
    ]
