# Generated by Django 3.2.6 on 2021-08-21 08:04

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20210821_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='biography',
            field=models.TextField(blank=True, default='', max_length=250, validators=[
                                   accounts.validators.linebreak_limit_biography], verbose_name='自己紹介'),
        ),
    ]
