# Generated by Django 3.2.6 on 2021-08-21 16:56

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_customuser_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='display_username',
            field=models.CharField(error_messages={'max_length': '20文字以内で入力してください。', 'unique': '既に登録されたユーザー名です。'}, help_text='入力した生のユーザーID（小文字変換なし）。', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['ASCII'], message='半角英数字またはアンダースコア（_）のみで入力してください。', regex='^[\\w]+\\Z')], verbose_name='表示ユーザー名'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'max_length': '20文字以内で入力してください。', 'unique': '既に登録されたユーザー名です。'}, help_text='20文字以内の半角英数字と，アンダースコア（_）のみ。', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['ASCII'], message='半角英語小文字・数字またはアンダースコア（_）のみで入力してください。', regex='^[a-z0-9_]+\\Z')], verbose_name='内部ユーザー名'),
        ),
    ]
