# Generated by Django 3.2.6 on 2021-08-23 12:24

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20210822_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_username',
            field=models.CharField(error_messages={'max_length': '20文字以内で入力してください。', 'unique': '既に登録されたユーザー名です。'}, help_text='入力した生のユーザーID（小文字変換なし）。', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['ASCII'], message='半角英数字またはアンダースコア（_）のみで入力してください。', regex='^[\\w_]+\\Z')], verbose_name='表示ユーザー名'),
        ),
    ]
