# Generated by Django 3.2.7 on 2021-09-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tart', '0004_tart_is_edited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tart',
            old_name='is_edited',
            new_name='was_edited',
        ),
    ]
