# Generated by Django 3.2.7 on 2021-09-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tart', '0005_rename_is_edited_tart_was_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='tart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
