# Generated by Django 3.2.7 on 2021-09-08 07:32

from django.db import migrations, models
import tart.validate


class Migration(migrations.Migration):

    dependencies = [
        ('tart', '0006_auto_20210907_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tart',
            name='text',
            field=models.TextField(max_length=140, validators=[tart.validate.linebreak_limit_tart], verbose_name='Tart内容'),
        ),
    ]
