# Generated by Django 3.2.7 on 2021-09-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tart', '0007_alter_tart_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tart',
            name='was_deleted',
            field=models.BooleanField(default=False, verbose_name='削除済'),
        ),
    ]
